#!/bin/bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

source "$SCRIPT_DIR/.venv/bin/activate"

if [ "$1" == "dev" ]; then
    pymon "$SCRIPT_DIR/main.py"
elif [ "$1" == "inspect" ]; then
    GTK_DEBUG=interactive python3 "$SCRIPT_DIR/main.py"   
else
    python3 "$SCRIPT_DIR/main.py"
fi
