# ==========================================
#  SHELL CONFIGURATION
#  Note: Only theme changes are live-loaded.
#  Restart the shell for all other changes.
# ==========================================

[general]
# Logging Level: "DEBUG", "INFO", "WARNING" (Default: "WARNING")
logging_level = "WARNING"

[clock]
# Time Format: Refer to https://strftime.org/
format = "%x %H:%M"

[theme]
# Theme Selection:
# • catppuccin-mocha  (Default)
# • adwaita           (GNOME Dark)
# • everforest        (Greenish)
# • gruvbox           (Retro Groove)
# • tokyo-night       (High Contrast Dark)
# • catppuccin-latte  (Light - experimental)
name = "catppuccin-mocha"

# Shell Accent: Hex color code (e.g., "#cba6f7")
accent = ""

# Appearance: Enable background transparency
transparency = true

# Font (Nerd Font recommended)
font = "MesloLGS Nerd Font"

[weather]
# Weather Service: Powered by wttr.in
enable = true

[sysmon]
# System Monitor Widget:
enable = true

# Update Frequency: Seconds between refreshes
interval = 2

# Click Action: Command to execute (Empty string to disable)
exec_on_click = "kitty -e btop"

# Visibility: Keep current info visible during warning thresholds
always_show_info = false

[keyboard-status]
# Currently only numpad is implemented
# Useful if you don't have physical LED on your numpad key
enable = false

[active-window]
# Displays active window's icon and title
# If you don't show anything, just set enable = false
enable = true
show_icon = true
show_title = false

[arch-update]
# Disabled outside of Arch-based distros
enable = true
